# Generated by Django 6.0.5 on 2026-05-27 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.CharField(max_length=255)),
                ('model_name', models.CharField(default='gemini-3.5-flash', max_length=100)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='stopped', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
